### ISSUE TITLE
Deleting Blade Runner and Alice and Wonderland

### ISSUE THREAD

**Issue by MinnickBridger** [catherineDiaz/Diaz_VanClief_Langdon_CSCI2270_FinalProject#1]
When I tried to delete Blade Runner and then reprint it, the program breaks. The same thing happens for Alice and Wonderland, I think they are both the root of the trees so maybe there is a problem with deleting a root node.

**Comment by catherineDiaz** [comment]
Yeah I don't think I remember putting a case in to delete the root

**Comment by snegri** [comment]
Could not build the project without adding return NULL on line 544. The searchByDirector function from MovieTree.cpp is missing a return.

**Comment by catherineDiaz** [comment]
Both issues are now fixed
